# Generated by Django 6.1 on 2026-08-24 22:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(db_index=True, max_length=255)),
                ('genre', models.CharField(blank=True, db_index=True, max_length=100)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)])),
                ('data_source', models.CharField(db_index=True, default='unknown', max_length=100)),
            ],
            options={
                'ordering': ['artist', 'title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrackFeatures',
            fields=[
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='features', serialize=False, to='recommendations.track')),
                ('tempo', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('energy', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('valence', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('danceability', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('acousticness', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('instrumentalness', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('loudness', models.FloatField()),
                ('speechiness', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('feature_source', models.CharField(default='unknown', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'track features',
            },
        ),
    ]
