# Generated by Django 6.1 on 2026-09-22 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_tracksuggestion_album_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='album_display',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='artist_display',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='recommendations.album'),
        ),
        migrations.AddField(
            model_name='track',
            name='primary_artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_tracks', to='recommendations.artist'),
        ),
        migrations.CreateModel(
            name='TrackArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='track_links', to='recommendations.artist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_artists', to='recommendations.track')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('track', 'artist'), name='unique_track_artist'), models.UniqueConstraint(fields=('track', 'position'), name='unique_track_artist_position')],
            },
        ),
    ]
