# Generated by Django 6.1 on 2026-09-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_album_artist_track_album_display_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
